name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Tests
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: npm install and test
      run: |
        npm install
        npm test
      env:
        CI: true
